import type { CaseDefinition } from "../types";

export const cases13to21: CaseDefinition[] = [
  {
    id: "case-013",
    version: 1,
    number: "13",
    title: "Back to the core",
    subtitle: "Too many bets. Too little cash.",
    category: "Turnaround",
    year: "2004",
    role: "You lead a toy maker.",
    objective: "Choose what to fund after a loss.",
    briefing:
      "Early 2004. Your toy firm lost money last year. It owns more than toys, including parks. You need a smaller bill without losing what kids love.",
    question: "Where should the next round of cuts fall?",
    evidence: [
      {
        id: "c13-e1",
        label: "Sales in 2003",
        text: "Sales were 7,196 million Danish kroner in 2003.",
        kind: "fact",
        sourceIds: ["c13-s1"],
      },
      {
        id: "c13-e2",
        label: "Core loss",
        text: "The 2003 loss before special items, finance costs and tax was 1,061 million kroner.",
        kind: "fact",
        sourceIds: ["c13-s1"],
      },
      {
        id: "c13-e3",
        label: "A wide bill",
        text: "Sales, shipping, admin and other running costs were 5,130 million kroner in 2003.",
        kind: "fact",
        sourceIds: ["c13-s1"],
      },
      {
        id: "c13-e4",
        label: "Cuts have started",
        text: "Work to cut admin, design and selling costs began in 2003.",
        kind: "fact",
        sourceIds: ["c13-s1"],
      },
    ],
    research: [
      {
        id: "c13-r1",
        title: "Check the parks",
        description: "See if the parks are all bad news.",
        hours: 1,
        evidence: [
          {
            id: "c13-e5",
            label: "Parks earned money",
            text: "The parks made 27 million kroner after tax in 2003.",
            kind: "fact",
            sourceIds: ["c13-s1"],
          },
          {
            id: "c13-e6",
            label: "Profit is not cash",
            text: "A profitable park may still need cash for upkeep. Selling it also gives up future income.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
      {
        id: "c13-r2",
        title: "Check the cost of cuts",
        description: "Look at bills already booked.",
        hours: 2,
        evidence: [
          {
            id: "c13-e7",
            label: "Earlier change costs",
            text: "The firm booked 283 million kroner in restructuring costs in 2003.",
            kind: "fact",
            sourceIds: ["c13-s1"],
          },
          {
            id: "c13-e8",
            label: "Cutting has a price",
            text: "A cut can save money later and use cash now. Pick a sequence, not just a target.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
      {
        id: "c13-r3",
        title: "Check toy lines",
        description: "Find the missing product view.",
        hours: 2,
        evidence: [
          {
            id: "c13-e9",
            label: "Margins not shown",
            text: "We do not have profit by toy line, age group or store. We cannot rank toys by sales alone.",
            kind: "unknown",
            sourceIds: [],
          },
          {
            id: "c13-e10",
            label: "Protect the play",
            text: "Test which parts kids use before cutting variety across every set.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
      {
        id: "c13-r4",
        title: "Plan a sale",
        description: "Work through a park sale and a cash plan.",
        hours: 3,
        evidence: [
          {
            id: "c13-e11",
            label: "Sale terms missing",
            text: "We have no firm park bid, debt terms or cash forecast for this decision.",
            kind: "unknown",
            sourceIds: [],
          },
          {
            id: "c13-e12",
            label: "Set a floor",
            text: "Set a minimum sale price and a cash reserve. A rushed sale can undo the gain from cuts.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
    ],
    suggestedQuestions: [
      "Check the parks?",
      "Check the cost of cuts?",
      "Check toy lines?",
      "Plan a sale?",
    ],
    event: {
      title: "A shared team",
      text: "At three hours, the design team says it can support one major reset this season.",
      evidence: {
        id: "c13-e13",
        label: "A shared team",
        text: "Choose between a simpler toy range and a large new theme launch. Splitting the team delays both.",
        kind: "simulation",
        sourceIds: [],
      },
    },
    options: [
      {
        id: "focus",
        title: "Shrink to core toys",
        description: "Cut side bets and seek buyers for the parks.",
        tradeoff: "Raises focus but may sell future earnings.",
      },
      {
        id: "toys",
        title: "Keep parks, cut toy lines",
        description: "Keep the parks and trim the least useful toy work.",
        tradeoff: "Keeps park earnings but leaves cash tied up.",
      },
      {
        id: "growth",
        title: "Fund a fresh theme",
        description: "Use new toys to try to restore sales.",
        tradeoff: "A hit could help, but launch costs come first.",
      },
      {
        id: "hold",
        title: "Hold the current plan",
        description: "Continue cuts already started; delay large sales.",
        tradeoff: "Buys time for bids while losses may continue.",
      },
    ],
    reveal: {
      company: "LEGO",
      identityAliases: ["LEGO", "LEGOLAND", "Knudstorp"],
      title: "A smaller toy firm",
      history:
        "LEGO launched a broad action plan in 2004. It cut costs and put classic building toys at the core. Its report also set out a plan to sell the parks.",
      lesson:
        "A business can earn a profit and still tie up cash you need elsewhere.",
      sources: [
        {
          id: "c13-s1",
          title: "LEGO Annual Report 2004, 2003 comparisons and action plan",
          url: "https://www.lego.com/cdn/cs/aboutus/assets/blt07abb4b8a3da3f39/Annual_Report_2004_ENG.pdf",
        },
      ],
      consequences: {
        focus:
          "You could free cash for toys. The sale price and timing still matter.",
        toys: "A smaller toy range could help. You still need money for park upkeep.",
        growth:
          "New toys could win kids back. Weak demand could make the cash gap worse.",
        hold: "You avoid a rushed sale. Set a date and cash limit for waiting.",
      },
      rubric: [
        "Did you separate park profit from cash needs?",
        "Did you allow for the cost of cuts?",
        "Did you avoid guessing which toy lines lose money?",
        "Did you set a cash limit and sale terms?",
      ],
    },
  },
  {
    id: "case-014",
    version: 1,
    number: "14",
    title: "Close the doors to learn",
    subtitle: "One evening of sales or one shared reset.",
    category: "Service quality",
    year: "2008",
    role: "You run a large coffee chain.",
    objective: "Choose how to teach better drink skills.",
    briefing:
      "Early February 2008. The chain has grown fast. You want staff to focus on coffee and care. A nationwide lesson would stop sales for an evening.",
    question: "How should the stores learn?",
    evidence: [
      {
        id: "c14-e1",
        label: "Fast growth",
        text: "The chain added 2,199 stores in fiscal 2006.",
        kind: "fact",
        sourceIds: ["c14-s1"],
      },
      {
        id: "c14-e2",
        label: "Two kinds of store",
        text: "It runs its own shops and also licenses shops to other firms.",
        kind: "fact",
        sourceIds: ["c14-s1"],
      },
      {
        id: "c14-e3",
        label: "A large footprint",
        text: "By fiscal 2006 it served customers in 37 countries.",
        kind: "fact",
        sourceIds: ["c14-s1"],
      },
      {
        id: "c14-e4",
        label: "Service matters",
        text: "Its 2006 plan tied sales growth to service, new drinks and faster work.",
        kind: "fact",
        sourceIds: ["c14-s1"],
      },
    ],
    research: [
      {
        id: "c14-r1",
        title: "Check the sales at stake",
        description: "See how much the firm depends on its own stores.",
        hours: 1,
        evidence: [
          {
            id: "c14-e5",
            label: "Own stores dominate",
            text: "Company-run stores brought in 85% of revenue in fiscal 2006.",
            kind: "fact",
            sourceIds: ["c14-s1"],
          },
          {
            id: "c14-e6",
            label: "Evening gap",
            text: "We do not have the sales or profit that this evening would lose.",
            kind: "unknown",
            sourceIds: [],
          },
        ],
      },
      {
        id: "c14-r2",
        title: "Check the growth model",
        description: "Separate new stores from better old stores.",
        hours: 2,
        evidence: [
          {
            id: "c14-e7",
            label: "Existing shops grew too",
            text: "Sales at comparable company-run stores rose 7% in fiscal 2006.",
            kind: "fact",
            sourceIds: ["c14-s1"],
          },
          {
            id: "c14-e8",
            label: "Old data has limits",
            text: "Those results do not tell us drink quality in February 2008. Use fresh checks before picking weak shops.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
      {
        id: "c14-r3",
        title: "Design the coffee lesson",
        description: "Choose what staff must do, not just hear.",
        hours: 2,
        evidence: [
          {
            id: "c14-e9",
            label: "Skill check",
            text: "Have staff make an espresso shot and steam milk. A manager can watch the work and coach each person.",
            kind: "interpretation",
            sourceIds: [],
          },
          {
            id: "c14-e10",
            label: "No skill scores",
            text: "We have no store-by-store drink tests or staff skill scores.",
            kind: "unknown",
            sourceIds: [],
          },
        ],
      },
      {
        id: "c14-r4",
        title: "Plan the follow-through",
        description: "Make a short lesson last.",
        hours: 3,
        evidence: [
          {
            id: "c14-e11",
            label: "One night is a start",
            text: "Use later drink checks and customer reports to see whether skills stick.",
            kind: "interpretation",
            sourceIds: [],
          },
          {
            id: "c14-e12",
            label: "Licensed shops differ",
            text: "A plan for shops you own does not automatically cover shops run by licensees.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
    ],
    suggestedQuestions: [
      "Check the sales at stake?",
      "Check the growth model?",
      "Design the coffee lesson?",
      "Plan the follow-through?",
    ],
    event: {
      title: "The shift problem",
      text: "At three hours, store leaders flag a problem with lessons held during normal trade.",
      evidence: {
        id: "c14-e13",
        label: "The shift problem",
        text: "Staff serving the queue cannot all practice together. A rolling lesson needs extra cover or more days.",
        kind: "simulation",
        sourceIds: [],
      },
    },
    options: [
      {
        id: "close",
        title: "Close for one evening",
        description: "Teach all company-run US shops at the same time.",
        tradeoff: "Clear shared focus, with lost trade.",
      },
      {
        id: "rotate",
        title: "Teach in shifts",
        description: "Keep doors open and train small groups.",
        tradeoff: "Keeps trade but needs cover.",
      },
      {
        id: "target",
        title: "Start at weak shops",
        description: "Check drink quality, then focus on low scores.",
        tradeoff: "Saves time but needs a fair test first.",
      },
      {
        id: "hold",
        title: "Keep normal training",
        description: "Delay a special event and use the current program.",
        tradeoff: "Avoids disruption but may leave skills uneven.",
      },
    ],
    reveal: {
      company: "Starbucks",
      identityAliases: ["Starbucks", "Howard Schultz"],
      title: "An evening for espresso",
      history:
        "Starbucks closed nearly 7,100 US company-run stores on the evening of February 26, 2008. Staff practiced espresso skills. The pause alone does not prove better service.",
      lesson: "A bold gesture needs a daily habit behind it.",
      sources: [
        {
          id: "c14-s1",
          title: "Starbucks 2006 Form 10-K/A, management overview",
          url: "https://www.sec.gov/Archives/edgar/data/829224/000089102006000418/v24294a1e10vkza.htm",
        },
        {
          id: "c14-s2",
          title:
            "Seattle Post-Intelligencer, February 26, 2008 on-site training report",
          url: "https://www.seattlepi.com/business/article/starbucks-gives-an-express-course-in-espresso-1265614.php",
        },
      ],
      consequences: {
        close:
          "A shared pause could make the lesson matter. Follow-up checks still decide if it works.",
        rotate:
          "You protect sales. Staff may get less practice unless cover is real.",
        target:
          "You can direct help where it is needed. Bad tests could miss weak shops.",
        hold: "You keep trade steady. Say what evidence would trigger extra training.",
      },
      rubric: [
        "Did you weigh lost trade against shared practice?",
        "Did you separate owned and licensed shops?",
        "Did you plan a hands-on skill test?",
        "Did you check results after the lesson?",
      ],
    },
  },
  {
    id: "case-015",
    version: 1,
    number: "15",
    title: "Ask buyers to buy less",
    subtitle: "A sales day meets a promise.",
    category: "Brand trust",
    year: "2011",
    role: "You lead an outdoor clothing firm.",
    objective: "Choose a holiday ad that fits your promise.",
    briefing:
      "November 2011. Your firm sells clothes and wants to cut harm to nature. The big holiday shopping day is near. A blunt ad could ask people to skip a purchase.",
    question: "What should the holiday ad say?",
    evidence: [
      {
        id: "c15-e1",
        label: "A growing firm",
        text: "The firm is opening stores and sending more catalogs.",
        kind: "fact",
        sourceIds: ["c15-s1"],
      },
      {
        id: "c15-e2",
        label: "Sales pay wages",
        text: "Staff pay depends on selling products.",
        kind: "fact",
        sourceIds: ["c15-s1"],
      },
      {
        id: "c15-e3",
        label: "A stated purpose",
        text: "The firm aims to help solve harm to the environment.",
        kind: "fact",
        sourceIds: ["c15-s1"],
      },
      {
        id: "c15-e4",
        label: "Even better cloth has costs",
        text: "Its own account says clothes made with recycled or organic material still use water and create waste.",
        kind: "fact",
        sourceIds: ["c15-s1"],
      },
    ],
    research: [
      {
        id: "c15-r1",
        title: "Check the earlier message",
        description: "Look for a past test of a blunt line.",
        hours: 1,
        evidence: [
          {
            id: "c15-e5",
            label: "A past catalog essay",
            text: "Years earlier, the firm used a headline that asked people not to buy a shirt.",
            kind: "fact",
            sourceIds: ["c15-s1"],
          },
          {
            id: "c15-e6",
            label: "A reported response",
            text: "The firm said that essay drew a strong response. It gave no sales test.",
            kind: "fact",
            sourceIds: ["c15-s1"],
          },
        ],
      },
      {
        id: "c15-r2",
        title: "Check the promise",
        description: "See what buyers would be asked to do.",
        hours: 2,
        evidence: [
          {
            id: "c15-e7",
            label: "A broader plan",
            text: "The firm has a plan built around using less, repair, reuse and recycling.",
            kind: "fact",
            sourceIds: ["c15-s1"],
          },
          {
            id: "c15-e8",
            label: "Words need service",
            text: "If the ad brings repair requests, the firm must be able to help.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
      {
        id: "c15-r3",
        title: "Check who sees the ad",
        description: "Weigh reach against clarity.",
        hours: 2,
        evidence: [
          {
            id: "c15-e9",
            label: "A headline can split",
            text: "Some readers may see only the warning. Others may read the full reason to buy less.",
            kind: "interpretation",
            sourceIds: [],
          },
          {
            id: "c15-e10",
            label: "No audience test",
            text: "We have no test of the new headline with holiday shoppers.",
            kind: "unknown",
            sourceIds: [],
          },
        ],
      },
      {
        id: "c15-r4",
        title: "Price the promise",
        description: "Look at the cost of fewer new sales.",
        hours: 3,
        evidence: [
          {
            id: "c15-e11",
            label: "No sales forecast",
            text: "We do not have the lost sales, repair load or repeat purchases this ad may cause.",
            kind: "unknown",
            sourceIds: [],
          },
          {
            id: "c15-e12",
            label: "Choose a real measure",
            text: "Track useful repairs and longer use as well as sales. Attention alone does not prove less waste.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
    ],
    suggestedQuestions: [
      "Check the earlier message?",
      "Check the promise?",
      "Check who sees the ad?",
      "Price the promise?",
    ],
    event: {
      title: "The small print shrinks",
      text: "At three hours, the ad team presents a tighter layout.",
      evidence: {
        id: "c15-e13",
        label: "The small print shrinks",
        text: "The bold line fits, but the full repair and reuse plan is hard to read. You can simplify the ad or choose a less blunt headline.",
        kind: "simulation",
        sourceIds: [],
      },
    },
    options: [
      {
        id: "blunt",
        title: "Ask people to skip buying",
        description: "Use a bold buy-less line and a clear repair plan.",
        tradeoff: "Gets attention but may seem at odds with selling clothes.",
      },
      {
        id: "care",
        title: "Lead with care and repair",
        description: "Show people how to make old gear last.",
        tradeoff: "Clear help with less shock.",
      },
      {
        id: "sale",
        title: "Run a normal product ad",
        description: "Sell durable gear and explain its uses.",
        tradeoff: "Supports sales but softens the buy-less goal.",
      },
      {
        id: "hold",
        title: "Skip this holiday ad",
        description: "Pause the ad and improve repair support first.",
        tradeoff: "Builds proof but loses the holiday moment.",
      },
    ],
    reveal: {
      company: "Patagonia",
      identityAliases: [
        "Patagonia",
        "Common Threads",
        "Worn Wear",
        "Yvon Chouinard",
      ],
      title: "A blunt holiday ad",
      history:
        "Patagonia ran “Don’t Buy This Jacket” on Black Friday 2011. It asked readers to buy less and care for gear. The source does not isolate what the ad did to sales or waste.",
      lesson: "Make sure your work can keep the promise your words make.",
      sources: [
        {
          id: "c15-s1",
          title:
            "Patagonia, November 25, 2011 ad explanation (later notes marked)",
          url: "https://www.patagonia.com/stories/planet/activism/dont-buy-this-jacket-black-friday-and-the-new-york-times/story-18615.html",
        },
      ],
      consequences: {
        blunt:
          "The line could earn trust if your service backs it. It could also confuse buyers.",
        care: "You give buyers a useful step. Fewer people may notice the ad.",
        sale: "You may sell useful gear. You must still face the cost of making more.",
        hold: "You can make the promise stronger. Give the pause a firm end date.",
      },
      rubric: [
        "Did you face the tension between sales and less buying?",
        "Did you give repair and reuse a clear next step?",
        "Did you avoid treating attention as less waste?",
        "Did you account for readers who see only the headline?",
      ],
    },
  },
  {
    id: "case-016",
    version: 1,
    number: "16",
    title: "A game for the whole room",
    subtitle: "Win old players or invite new ones.",
    category: "Market choice",
    year: "2006",
    role: "You lead a game console launch.",
    objective: "Choose whom the launch should serve first.",
    briefing:
      "Mid-2006. Your new home console has a new kind of remote control. Your handheld games have reached new players. You must pick the main audience for the home launch.",
    question: "Who should the launch aim at?",
    evidence: [
      {
        id: "c16-e1",
        label: "A new control",
        text: "The planned home console uses a remote built to make play easier.",
        kind: "fact",
        sourceIds: ["c16-s1"],
      },
      {
        id: "c16-e2",
        label: "Touch has worked",
        text: "The firm already sells a handheld with a touch screen and microphone.",
        kind: "fact",
        sourceIds: ["c16-s1"],
      },
      {
        id: "c16-e3",
        label: "New players",
        text: "Its handheld games have reached older people and women.",
        kind: "fact",
        sourceIds: ["c16-s1"],
      },
      {
        id: "c16-e4",
        label: "Home sales fell",
        text: "Sales of its current home console and its games fell in the year to March 2006.",
        kind: "fact",
        sourceIds: ["c16-s1"],
      },
    ],
    research: [
      {
        id: "c16-r1",
        title: "Check the handheld reach",
        description: "See how much proof the small screen offers.",
        hours: 1,
        evidence: [
          {
            id: "c16-e5",
            label: "More than 16 million",
            text: "The handheld and its new version sold over 16 million units in just over sixteen months.",
            kind: "fact",
            sourceIds: ["c16-s1"],
          },
          {
            id: "c16-e6",
            label: "Different room",
            text: "Handheld success does not prove a whole household will buy a home console.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
      {
        id: "c16-r2",
        title: "Check a simple game",
        description: "Look at a game outside the usual action race.",
        hours: 2,
        evidence: [
          {
            id: "c16-e7",
            label: "Pet game sales",
            text: "Its virtual-pet game series sold 6.65 million units by March 2006.",
            kind: "fact",
            sourceIds: ["c16-s1"],
          },
          {
            id: "c16-e8",
            label: "A reason to try",
            text: "Simple controls still need a game people want to play. Ease alone is not a full offer.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
      {
        id: "c16-r3",
        title: "Check launch demos",
        description: "Design a fair first try.",
        hours: 2,
        evidence: [
          {
            id: "c16-e9",
            label: "The demo test",
            text: "Watch a new player start without help. Then see if they ask for another turn.",
            kind: "interpretation",
            sourceIds: [],
          },
          {
            id: "c16-e10",
            label: "No living-room test",
            text: "We have no home trial results or repeat-use rates for the new console.",
            kind: "unknown",
            sourceIds: [],
          },
        ],
      },
      {
        id: "c16-r4",
        title: "Check the games supply",
        description: "Look beyond the first day.",
        hours: 3,
        evidence: [
          {
            id: "c16-e11",
            label: "Missing launch costs",
            text: "We have no full launch budget or cost for each game plan.",
            kind: "unknown",
            sourceIds: [],
          },
          {
            id: "c16-e12",
            label: "A steady reason to return",
            text: "A wide launch needs games for new players after the first demo. Keep a path for skilled players too.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
    ],
    suggestedQuestions: [
      "Check the handheld reach?",
      "Check a simple game?",
      "Check launch demos?",
      "Check the games supply?",
    ],
    event: {
      title: "One front window",
      text: "At three hours, a key retailer offers space for one main launch demo.",
      evidence: {
        id: "c16-e13",
        label: "One front window",
        text: "Choose a quick shared game or a deep solo game. The other can still sell, but it will not lead the display.",
        kind: "simulation",
        sourceIds: [],
      },
    },
    options: [
      {
        id: "family",
        title: "Lead with shared play",
        description: "Use simple group games to welcome new players.",
        tradeoff: "Broad reach but may seem shallow to skilled fans.",
      },
      {
        id: "core",
        title: "Lead with skilled fans",
        description: "Use deep games and familiar ways to play.",
        tradeoff: "Clear demand but less proof of a wider audience.",
      },
      {
        id: "both",
        title: "Split the launch",
        description: "Give new and skilled players equal space.",
        tradeoff: "More choice but less clear message.",
      },
      {
        id: "hold",
        title: "Delay the big campaign",
        description: "Run small demos before committing the full launch spend.",
        tradeoff: "Buys proof but may lose launch momentum.",
      },
    ],
    reveal: {
      company: "Nintendo",
      identityAliases: ["Nintendo", "Wii", "DS Lite", "Nintendogs", "Iwata"],
      title: "A wider welcome",
      history:
        "Nintendo launched Wii in 2006. Its plan centered on easy control and play for the whole household. That choice followed evidence from its touch-based handheld games.",
      lesson: "A new audience needs an easy first step and a reason to return.",
      sources: [
        {
          id: "c16-s1",
          title:
            "Nintendo Annual Report 2006, president letter and operations review",
          url: "https://www.nintendo.co.jp/kessan/annual0603e.pdf",
        },
        {
          id: "c16-s2",
          title: "Nintendo Wii controller record, launch date",
          url: "https://www.nintendo.co.jp/wii/controllers/index.html",
        },
      ],
      consequences: {
        family:
          "You could bring new people in. You need games that keep them playing.",
        core: "You keep a trusted group close. The new control may reach fewer new buyers.",
        both: "Both groups get a reason to care. The shop demo needs one clear first step.",
        hold: "You can learn from real tries. Set a decision date so testing does not drift.",
      },
      rubric: [
        "Did you separate handheld proof from home demand?",
        "Did you choose a clear first audience?",
        "Did you plan repeat use after the demo?",
        "Did you address the one-demo constraint?",
      ],
    },
  },
  {
    id: "case-017",
    version: 1,
    number: "17",
    title: "The price of entry",
    subtitle: "A small fee change for millions.",
    category: "Pricing",
    year: "2017",
    role: "You lead a members-only warehouse chain.",
    objective: "Choose a fair fee plan without losing members.",
    briefing:
      "March 2017, before the fee announcement. Sales are up, but quarterly profit is down. Members pay each year to shop. You are weighing a rise in that fee.",
    question: "How should membership fees change?",
    evidence: [
      {
        id: "c17-e1",
        label: "The basic fee",
        text: "The current basic annual fee in the US and Canada is $55.",
        kind: "fact",
        sourceIds: ["c17-s1"],
      },
      {
        id: "c17-e2",
        label: "The top fee",
        text: "The higher tier costs $110 a year.",
        kind: "fact",
        sourceIds: ["c17-s1"],
      },
      {
        id: "c17-e3",
        label: "Sales grew",
        text: "Sales in the quarter ended February 12 rose 6% to $29.13 billion.",
        kind: "fact",
        sourceIds: ["c17-s1"],
      },
      {
        id: "c17-e4",
        label: "Profit fell",
        text: "Quarterly net income was $515 million, down from $546 million a year before.",
        kind: "fact",
        sourceIds: ["c17-s1"],
      },
    ],
    research: [
      {
        id: "c17-r1",
        title: "Check the reward",
        description: "See what the higher tier gives back.",
        hours: 1,
        evidence: [
          {
            id: "c17-e5",
            label: "A reward limit",
            text: "The higher tier has a 2% reward with a $750 annual cap.",
            kind: "fact",
            sourceIds: ["c17-s1"],
          },
          {
            id: "c17-e6",
            label: "Different users",
            text: "Raising the cap helps big spenders most. A light shopper may see no extra value.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
      {
        id: "c17-r2",
        title: "Check how many pay",
        description: "Size the proposed change.",
        hours: 2,
        evidence: [
          {
            id: "c17-e7",
            label: "About 35 million",
            text: "A US and Canada fee rise would touch about 35 million members. Roughly half use the higher tier.",
            kind: "fact",
            sourceIds: ["c17-s1"],
          },
          {
            id: "c17-e8",
            label: "Scale cuts both ways",
            text: "A small fee change can add revenue across many members. A small loss of members can also matter.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
      {
        id: "c17-r3",
        title: "Check why profit fell",
        description: "Avoid solving the wrong problem.",
        hours: 2,
        evidence: [
          {
            id: "c17-e9",
            label: "No cause shown here",
            text: "The sales and net income totals alone do not explain the profit drop.",
            kind: "unknown",
            sourceIds: [],
          },
          {
            id: "c17-e10",
            label: "Separate the jobs",
            text: "A fee rise can add income. It cannot by itself fix weak store costs or a poor shopping trip.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
      {
        id: "c17-r4",
        title: "Test who might leave",
        description: "Plan the response to a higher bill.",
        hours: 3,
        evidence: [
          {
            id: "c17-e11",
            label: "No price test",
            text: "We have no estimate of cancellations at $60 or $120.",
            kind: "unknown",
            sourceIds: [],
          },
          {
            id: "c17-e12",
            label: "Watch both tiers",
            text: "Track renewals and downgrades by tier. A stable total can hide a loss of higher-paying members.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
    ],
    suggestedQuestions: [
      "Check the reward?",
      "Check how many pay?",
      "Check why profit fell?",
      "Test who might leave?",
    ],
    event: {
      title: "The notice deadline",
      text: "At three hours, the member team needs the next renewal notice.",
      evidence: {
        id: "c17-e13",
        label: "The notice deadline",
        text: "It can show a price rise now or keep the old fee for this batch. A later change means another round of notices.",
        kind: "simulation",
        sourceIds: [],
      },
    },
    options: [
      {
        id: "raise",
        title: "Raise both tiers",
        description: "Move fees to $60 and $120; lift the reward cap.",
        tradeoff: "More income, with a risk of fewer renewals.",
      },
      {
        id: "basic",
        title: "Raise only the basic tier",
        description: "Move the basic fee to $60 and keep the top tier at $110.",
        tradeoff: "Makes upgrades easier but puts the rise on light users.",
      },
      {
        id: "top",
        title: "Raise only the top tier",
        description: "Keep basic at $55; charge $120 with a higher reward cap.",
        tradeoff: "Protects entry price but asks more of top members.",
      },
      {
        id: "hold",
        title: "Keep fees unchanged",
        description: "Study renewal risk before the next fee review.",
        tradeoff: "Keeps trust steady but gives up near-term fee income.",
      },
    ],
    reveal: {
      company: "Costco",
      identityAliases: [
        "Costco",
        "Gold Star",
        "Goldstar",
        "Executive Membership",
      ],
      title: "A rise in both tiers",
      history:
        "Costco announced fees of $60 and $120 from June 1, 2017. It also raised the top tier’s reward cap to $1,000. The announcement did not prove future renewal behavior.",
      lesson: "Judge a fee through the value each kind of member gets.",
      sources: [
        {
          id: "c17-s1",
          title: "Costco March 2, 2017 results and fee announcement",
          url: "https://investor.costco.com/news/news-details/2017/Costco-Wholesale-Corporation-Reports-Second-Quarter-and-Year-to-Date-Operating-Results-for-Fiscal-Year-2017-February-Sales-Results-and-Plans-for-Membership-Fee-Increase-03-02-2017/default.aspx",
        },
      ],
      consequences: {
        raise:
          "The rise could fund value in stores. Watch whether members still see a fair deal.",
        basic:
          "You may draw upgrades. Basic members could feel they bear the cost.",
        top: "Big spenders may value the cap. Others may downgrade.",
        hold: "You avoid a new price shock. Pick the evidence and date for a review.",
      },
      rubric: [
        "Did you separate sales growth from the profit drop?",
        "Did you consider light and heavy shoppers?",
        "Did you plan to watch renewals and downgrades?",
        "Did you explain what members get for more money?",
      ],
    },
  },
  {
    id: "case-018",
    version: 1,
    number: "18",
    title: "A table in a small box",
    subtitle: "Save on shipping. Ask buyers to build.",
    category: "Operations",
    year: "1956",
    role: "You lead a mail-order furniture firm.",
    objective: "Choose how far to take home assembly.",
    briefing:
      "You are planning the 1956 range. Tables can be costly to ship and can arrive damaged. Some of your tables already come apart. Should more of the range follow?",
    question: "How should you ship the next tables?",
    evidence: [
      {
        id: "c18-e1",
        label: "Delivery is hard",
        text: "The founder had faced costly, complex furniture shipping.",
        kind: "fact",
        sourceIds: ["c18-s1"],
      },
      {
        id: "c18-e2",
        label: "Damage on the road",
        text: "Tables were among the goods damaged in transport.",
        kind: "fact",
        sourceIds: ["c18-s1"],
      },
      {
        id: "c18-e3",
        label: "A proven start",
        text: "The 1953 catalog already offered three tables for home assembly.",
        kind: "fact",
        sourceIds: ["c18-s1"],
      },
      {
        id: "c18-e4",
        label: "Not a new invention",
        text: "A Swedish department store offered a flatpack range in 1944.",
        kind: "fact",
        sourceIds: ["c18-s1"],
      },
    ],
    research: [
      {
        id: "c18-r1",
        title: "Check the fittings",
        description: "See what made the early tables possible.",
        hours: 1,
        evidence: [
          {
            id: "c18-e5",
            label: "A supplier showed a way",
            text: "A supplier showed the firm a sturdy table with fittings that made home assembly easier.",
            kind: "fact",
            sourceIds: ["c18-s1"],
          },
          {
            id: "c18-e6",
            label: "A useful boundary",
            text: "A strong joint matters as much as a small box. Do not cut packing size at the cost of safe use.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
      {
        id: "c18-r2",
        title: "Check the rival model",
        description: "Look at how people normally buy furniture.",
        hours: 2,
        evidence: [
          {
            id: "c18-e7",
            label: "Long waits",
            text: "Traditional furniture shops could make customers wait weeks or months for delivery.",
            kind: "fact",
            sourceIds: ["c18-s1"],
          },
          {
            id: "c18-e8",
            label: "Two kinds of value",
            text: "A lower price and quicker delivery could repay some of the work buyers must do.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
      {
        id: "c18-r3",
        title: "Check the home task",
        description: "Make the buyer’s job clear.",
        hours: 2,
        evidence: [
          {
            id: "c18-e9",
            label: "No assembly scores",
            text: "We have no timed home tests, error rates or return rates for the next range.",
            kind: "unknown",
            sourceIds: [],
          },
          {
            id: "c18-e10",
            label: "Test without coaching",
            text: "Give a first-time buyer the box and guide. Watch where they get stuck before expanding.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
      {
        id: "c18-r4",
        title: "Check the full cost",
        description: "Count both ends of the trip.",
        hours: 3,
        evidence: [
          {
            id: "c18-e11",
            label: "No cost table",
            text: "We do not have freight savings, extra packing costs or after-sale help costs by table.",
            kind: "unknown",
            sourceIds: [],
          },
          {
            id: "c18-e12",
            label: "A whole-trip test",
            text: "Compare a finished table with a boxed kit from factory to home. Include broken parts and failed assembly.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
    ],
    suggestedQuestions: [
      "Check the fittings?",
      "Check the rival model?",
      "Check the home task?",
      "Check the full cost?",
    ],
    event: {
      title: "A fitting is changed",
      text: "At three hours, the supplier offers a smaller fitting for the next table.",
      evidence: {
        id: "c18-e13",
        label: "A fitting is changed",
        text: "It saves space in the box, but has not passed a home assembly test. You can keep the older fitting or delay this table.",
        kind: "simulation",
        sourceIds: [],
      },
    },
    options: [
      {
        id: "expand",
        title: "Expand home assembly",
        description: "Use proven fittings on more tables.",
        tradeoff: "Smaller boxes but more work for buyers.",
      },
      {
        id: "pilot",
        title: "Test one more table",
        description: "Run a small home trial before a broad change.",
        tradeoff: "Slower savings, with less risk.",
      },
      {
        id: "built",
        title: "Ship tables built",
        description: "Keep most tables ready to use on arrival.",
        tradeoff: "Less buyer work, more shipping bulk.",
      },
      {
        id: "hold",
        title: "Keep the current mix",
        description: "Keep the three existing kits and defer new ones.",
        tradeoff: "Avoids new problems but limits savings.",
      },
    ],
    reveal: {
      company: "IKEA",
      identityAliases: [
        "IKEA",
        "LÖVET",
        "LOVET",
        "Kamprad",
        "DELFI",
        "KÖKSA",
        "RIGA",
      ],
      title: "Flatpacks were already in use",
      history:
        "IKEA had self-assembly tables in its 1953 catalog. The LÖVET table appeared in the 1956 catalog and became a noted early flatpack. It was not the first.",
      lesson:
        "Saving your own work helps only if the buyer’s new task is worth it.",
      sources: [
        {
          id: "c18-s1",
          title: "IKEA Museum, Flatpacks history",
          url: "https://ikeamuseum.com/en/explore/the-story-of-ikea/flatpacks/",
        },
        {
          id: "c18-s2",
          title: "IKEA Museum, LÖVET product history",
          url: "https://ikeamuseum.com/en/explore/product-stories/lovet-coffee-table-1956/",
        },
      ],
      consequences: {
        expand:
          "You could cut shipping costs. Clear guides and complete kits must support the price.",
        pilot:
          "You learn where buyers struggle. Set clear pass marks for expansion.",
        built:
          "Some buyers may pay for ease. You still need to address shipping damage.",
        hold: "You preserve a known range. Define what would make the next kit ready.",
      },
      rubric: [
        "Did you count shipping damage and home assembly?",
        "Did you use the 1953 products as evidence, not claim a first invention?",
        "Did you test the new fitting?",
        "Did you include help and returns in cost?",
      ],
    },
  },
  {
    id: "case-019",
    version: 1,
    number: "19",
    title: "Pay for people to stay",
    subtitle: "A fast line needs a steady team.",
    category: "Workforce",
    year: "1914",
    role: "You lead a car factory.",
    objective: "Keep a trained team while controlling cost.",
    briefing:
      "Early January 1914. A moving line speeds up car work. But workers leave, and the pace causes mistakes. A large pay rise is on the table.",
    question: "What should you change first?",
    evidence: [
      {
        id: "c19-e1",
        label: "The line is moving",
        text: "The firm began using a moving car assembly line in 1913.",
        kind: "fact",
        sourceIds: ["c19-s1"],
      },
      {
        id: "c19-e2",
        label: "Smaller tasks",
        text: "Workers now repeat one or two tasks rather than build a whole car.",
        kind: "fact",
        sourceIds: ["c19-s1"],
      },
      {
        id: "c19-e3",
        label: "People leave",
        text: "Workers have left for rival firms after finding the line work dull.",
        kind: "fact",
        sourceIds: ["c19-s1"],
      },
      {
        id: "c19-e4",
        label: "A strict pace",
        text: "Workers struggle to finish before a car moves to the next station.",
        kind: "fact",
        sourceIds: ["c19-s1"],
      },
    ],
    research: [
      {
        id: "c19-r1",
        title: "Check the quality cost",
        description: "Look beyond cars per hour.",
        hours: 1,
        evidence: [
          {
            id: "c19-e5",
            label: "Parts get missed",
            text: "Cars have left a station with missing parts as workers struggle with the pace.",
            kind: "fact",
            sourceIds: ["c19-s1"],
          },
          {
            id: "c19-e6",
            label: "Speed can mislead",
            text: "A fast line is not a gain if later work must fix mistakes.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
      {
        id: "c19-r2",
        title: "Check how the line works",
        description: "See what is hard to change.",
        hours: 2,
        evidence: [
          {
            id: "c19-e7",
            label: "Work comes to people",
            text: "The line first used a rope and later a moving chain to carry the car.",
            kind: "fact",
            sourceIds: ["c19-s1"],
          },
          {
            id: "c19-e8",
            label: "One change spreads",
            text: "Slowing the line affects the whole flow. Better staffing may help without changing every station.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
      {
        id: "c19-r3",
        title: "Check the pay plan",
        description: "Work through cost and fairness.",
        hours: 2,
        evidence: [
          {
            id: "c19-e9",
            label: "No full pay model",
            text: "We have no forecast linking a $5 day to quits, output or total wage cost.",
            kind: "unknown",
            sourceIds: [],
          },
          {
            id: "c19-e10",
            label: "Make rules clear",
            text: "A bonus with unclear rules may not feel like a pay rise. State who qualifies and when.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
      {
        id: "c19-r4",
        title: "Check work design",
        description: "Compare pay with a better shift.",
        hours: 3,
        evidence: [
          {
            id: "c19-e11",
            label: "No controlled trial",
            text: "We have no test comparing more pay, shorter shifts and task changes at this factory.",
            kind: "unknown",
            sourceIds: [],
          },
          {
            id: "c19-e12",
            label: "Watch the whole team",
            text: "Track quits, missed parts and injuries alongside output. More hires alone does not mean people will stay.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
    ],
    suggestedQuestions: [
      "Check the quality cost?",
      "Check how the line works?",
      "Check the pay plan?",
      "Check work design?",
    ],
    event: {
      title: "A shift has gaps",
      text: "At three hours, the shift lead reports empty stations for the next run.",
      evidence: {
        id: "c19-e13",
        label: "A shift has gaps",
        text: "You can slow the line with the current team or bring in new hires who still need coaching.",
        kind: "simulation",
        sourceIds: [],
      },
    },
    options: [
      {
        id: "pay",
        title: "Offer a $5 day",
        description:
          "Use higher pay with clear, fair terms to help retain staff.",
        tradeoff: "Higher wage bills before gains are known.",
      },
      {
        id: "pace",
        title: "Improve the work first",
        description: "Slow the line and try shorter or varied tasks.",
        tradeoff: "Better work may mean fewer cars at first.",
      },
      {
        id: "hire",
        title: "Hire and train more",
        description: "Keep pay steady and build a larger trained pool.",
        tradeoff: "Adds cover but can repeat a cycle of quits.",
      },
      {
        id: "hold",
        title: "Keep the current system",
        description: "Wait for more output and quit data.",
        tradeoff: "Avoids a large wage promise while gaps remain.",
      },
    ],
    reveal: {
      company: "Ford",
      identityAliases: ["Ford", "Model T", "Highland Park"],
      title: "The five-dollar day",
      history:
        "Ford introduced the $5 day in 1914, using profit-sharing payments. It also cut the shift by an hour. More people sought jobs, but pay and work design were separate parts of the change.",
      lesson:
        "Count the cost of losing people, not just the cost of paying them.",
      sources: [
        {
          id: "c19-s1",
          title: "Ford, The Moving Assembly Line and the Five-Dollar Workday",
          url: "https://corporate.ford.com/articles/history/moving-assembly-line/",
        },
      ],
      consequences: {
        pay: "More workers may stay. Pay alone may not fix dull or unsafe work.",
        pace: "The job may become easier to keep. You still need to know if pay is enough.",
        hire: "Extra cover could fill gaps. High turnover could keep training costs high.",
        hold: "You can gather clearer numbers. Set a short deadline while the line is under strain.",
      },
      rubric: [
        "Did you connect quits to line quality and training?",
        "Did you address the empty stations?",
        "Did you distinguish pay from working conditions?",
        "Did you define who gets the pay and how success is checked?",
      ],
    },
  },
  {
    id: "case-020",
    version: 1,
    number: "20",
    title: "Teach a rival your craft",
    subtitle: "A local foothold has a price.",
    category: "Partnership",
    year: "1984",
    role: "You lead a Japanese car maker.",
    objective: "Choose a way to learn US production.",
    briefing:
      "January 1984. An American rival wants to share a closed plant. A deal has early approval. You could learn to build cars in the US, but your partner could learn your methods too.",
    question: "Should you fund the shared plant?",
    evidence: [
      {
        id: "c20-e1",
        label: "An earlier deal failed",
        text: "Talks with a different US car maker broke down in July 1981.",
        kind: "fact",
        sourceIds: ["c20-s1"],
      },
      {
        id: "c20-e2",
        label: "Trade limits",
        text: "Limits on Japanese car exports to the US began in fiscal 1981.",
        kind: "fact",
        sourceIds: ["c20-s1"],
      },
      {
        id: "c20-e3",
        label: "A shared plan",
        text: "A 1983 agreement proposed equal ownership of a closed California plant.",
        kind: "fact",
        sourceIds: ["c20-s1"],
      },
      {
        id: "c20-e4",
        label: "Early approval",
        text: "The US trade regulator gave provisional approval in December 1983.",
        kind: "fact",
        sourceIds: ["c20-s1"],
      },
    ],
    research: [
      {
        id: "c20-r1",
        title: "Check the partner’s need",
        description: "See why the rival wants the deal.",
        hours: 1,
        evidence: [
          {
            id: "c20-e5",
            label: "Small-car gap",
            text: "The US partner wanted more small cars and the skill to make them.",
            kind: "fact",
            sourceIds: ["c20-s1"],
          },
          {
            id: "c20-e6",
            label: "Learning goes both ways",
            text: "The skills that make you a useful partner are also the skills a rival wants.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
      {
        id: "c20-r2",
        title: "Check the deal limits",
        description: "Look at scale and time.",
        hours: 2,
        evidence: [
          {
            id: "c20-e7",
            label: "A bounded term",
            text: "The 1983 plan targeted about 200,000 cars a year and a term of no more than 12 years.",
            kind: "fact",
            sourceIds: ["c20-s1"],
          },
          {
            id: "c20-e8",
            label: "A target is not demand",
            text: "The plant target does not prove orders, quality or profit.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
      {
        id: "c20-r3",
        title: "Check the inside objections",
        description: "Look at what your own teams fear.",
        hours: 2,
        evidence: [
          {
            id: "c20-e9",
            label: "Methods and models",
            text: "Production staff feared sharing know-how. Sales staff worried about giving a leading model to a rival.",
            kind: "fact",
            sourceIds: ["c20-s1"],
          },
          {
            id: "c20-e10",
            label: "Draw a boundary",
            text: "Specify which methods are shared and who can use them outside the plant.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
      {
        id: "c20-r4",
        title: "Check the people plan",
        description: "Study what local production must learn.",
        hours: 3,
        evidence: [
          {
            id: "c20-e11",
            label: "Union work matters",
            text: "Working with the US auto union was a major issue in the talks.",
            kind: "fact",
            sourceIds: ["c20-s1"],
          },
          {
            id: "c20-e12",
            label: "Missing terms",
            text: "We do not have the final work rules, training bill or detailed exit terms.",
            kind: "unknown",
            sourceIds: [],
          },
        ],
      },
    ],
    suggestedQuestions: [
      "Check the partner’s need?",
      "Check the deal limits?",
      "Check the inside objections?",
      "Check the people plan?",
    ],
    event: {
      title: "A wider training request",
      text: "At three hours, the partner asks to send more managers through your production training.",
      evidence: {
        id: "c20-e13",
        label: "A wider training request",
        text: "More learners may help the plant start. They may also carry more of your methods back to other plants.",
        kind: "simulation",
        sourceIds: [],
      },
    },
    options: [
      {
        id: "join",
        title: "Fund the joint plant",
        description:
          "Share ownership and train the new team with clear limits.",
        tradeoff: "Local learning in return for sharing know-how.",
      },
      {
        id: "own",
        title: "Build your own US plant",
        description: "Keep control and learn without a rival inside.",
        tradeoff: "More control, more cost and risk alone.",
      },
      {
        id: "license",
        title: "Offer a narrow license",
        description: "Sell a model or parts without a shared plant.",
        tradeoff: "Less exposure, less direct local learning.",
      },
      {
        id: "hold",
        title: "Wait before funding",
        description: "Keep exports and seek tighter deal terms.",
        tradeoff: "Preserves cash while trade limits remain.",
      },
    ],
    reveal: {
      company: "Toyota",
      identityAliases: [
        "Toyota",
        "NUMMI",
        "General Motors",
        "Corolla",
        "Toyoda",
      ],
      title: "A plant shared with a rival",
      history:
        "Toyota and GM formed NUMMI in February 1984 with equal shares of $200 million in capital. Toyota’s history describes it as a way to learn US production while sharing risk.",
      lesson:
        "A good partner brings what you need. Decide what you are willing to teach in return.",
      sources: [
        {
          id: "c20-s1",
          title: "Toyota 75-year history, Joint Venture with GM",
          url: "https://www.toyota-global.com/company/history_of_toyota/75years/text/leaping_forward_as_a_global_corporation/chapter1/section3/item2.html",
        },
      ],
      consequences: {
        join: "You could learn US production with a partner. Set rights and training terms before work starts.",
        own: "You keep methods closer. You must fund and learn local operations yourself.",
        license:
          "You may earn revenue with less commitment. You lose some hands-on learning.",
        hold: "You can seek better terms. Waiting also delays a local foothold.",
      },
      rubric: [
        "Did you state what each side wants to learn?",
        "Did you weigh shared risk against shared know-how?",
        "Did you address union work and training?",
        "Did you set terms for access and exit?",
      ],
    },
  },
  {
    id: "case-021",
    version: 1,
    number: "21",
    title: "Build it under your own name",
    subtitle: "A new cleaner needs a route to homes.",
    category: "Go to market",
    year: "1993",
    role: "You are a vacuum inventor.",
    objective: "Choose how to bring a bagless cleaner to Britain.",
    briefing:
      "Early 1993. Your design can collect dust without a throwaway bag. A version has sold in Japan. European makers have turned down a license. You could make it yourself.",
    question: "How should the cleaner reach buyers?",
    evidence: [
      {
        id: "c21-e1",
        label: "A blocked bag",
        text: "The idea began when dust clogged the pores in the inventor’s vacuum bag.",
        kind: "fact",
        sourceIds: ["c21-s1"],
      },
      {
        id: "c21-e2",
        label: "A borrowed idea",
        text: "The inventor tried a small cyclone based on machines used in sawmills.",
        kind: "fact",
        sourceIds: ["c21-s1"],
      },
      {
        id: "c21-e3",
        label: "Many tries",
        text: "The company’s history counts 5,127 prototypes before the earlier bagless model.",
        kind: "fact",
        sourceIds: ["c21-s1"],
      },
      {
        id: "c21-e4",
        label: "A market abroad",
        text: "An earlier bagless cleaner was sold in Japan.",
        kind: "fact",
        sourceIds: ["c21-s1"],
      },
    ],
    research: [
      {
        id: "c21-r1",
        title: "Check the refusals",
        description: "See what the makers had to lose.",
        hours: 1,
        evidence: [
          {
            id: "c21-e5",
            label: "Bag revenue mattered",
            text: "The company says European makers feared losing profit from replacement bags.",
            kind: "fact",
            sourceIds: ["c21-s1"],
          },
          {
            id: "c21-e6",
            label: "Refusal is not a vote",
            text: "A maker protecting bag sales is not the same as a buyer rejecting the cleaner.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
      {
        id: "c21-r2",
        title: "Check the early test",
        description: "Look at what the first build showed.",
        hours: 2,
        evidence: [
          {
            id: "c21-e7",
            label: "A simple first build",
            text: "The inventor made the first small cyclone trial with cardboard and tape.",
            kind: "fact",
            sourceIds: ["c21-s1"],
          },
          {
            id: "c21-e8",
            label: "A test has limits",
            text: "A working early model does not prove a factory can make thousands at a profit.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
      {
        id: "c21-r3",
        title: "Plan the factory",
        description: "List the jobs a licensee would have done.",
        hours: 2,
        evidence: [
          {
            id: "c21-e9",
            label: "No factory budget",
            text: "We have no unit cost, factory budget or confirmed retailer orders.",
            kind: "unknown",
            sourceIds: [],
          },
          {
            id: "c21-e10",
            label: "More than making it",
            text: "An own-brand launch also needs repairs, spare parts and a way for buyers to get help.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
      {
        id: "c21-r4",
        title: "Test the sales pitch",
        description: "Find proof a buyer can see.",
        hours: 3,
        evidence: [
          {
            id: "c21-e11",
            label: "No British price test",
            text: "We have no trial of what British buyers will pay for this cleaner.",
            kind: "unknown",
            sourceIds: [],
          },
          {
            id: "c21-e12",
            label: "Show the benefit",
            text: "A live dust test can explain the bagless design. Compare long use, not only a fresh machine.",
            kind: "interpretation",
            sourceIds: [],
          },
        ],
      },
    ],
    suggestedQuestions: [
      "Check the refusals?",
      "Check the early test?",
      "Plan the factory?",
      "Test the sales pitch?",
    ],
    event: {
      title: "An offer with strings",
      text: "At three hours, a potential partner offers to handle sales if it controls the product name and service plan.",
      evidence: {
        id: "c21-e13",
        label: "An offer with strings",
        text: "You could reach shops sooner, but buyers would know the partner’s name and depend on its repairs.",
        kind: "simulation",
        sourceIds: [],
      },
    },
    options: [
      {
        id: "own",
        title: "Launch your own brand",
        description:
          "Build a small production run and sell with your own service plan.",
        tradeoff: "More control, more cash and work at risk.",
      },
      {
        id: "license",
        title: "Keep seeking a license",
        description: "Find a maker with less reason to protect bag sales.",
        tradeoff: "Less factory risk, less control.",
      },
      {
        id: "partner",
        title: "Share the route to shops",
        description: "Use a sales partner with clear brand and service terms.",
        tradeoff: "Quicker reach, split control.",
      },
      {
        id: "hold",
        title: "Stay with the current market",
        description: "Keep the Japan route and delay a British launch.",
        tradeoff: "Less new risk but slower learning at home.",
      },
    ],
    reveal: {
      company: "Dyson",
      identityAliases: ["Dyson", "G-Force", "DC01", "James Dyson"],
      title: "An own-brand launch",
      history:
        "Dyson made and launched the DC01 in 1993. Its company timeline records the first unit leaving its own Chippenham line on July 1. Building it also meant owning production and support.",
      lesson:
        "Ask why a partner says no. Their lost revenue may be your buyer’s gain.",
      sources: [
        {
          id: "c21-s1",
          title: "Dyson official company timeline",
          url: "https://careers.dyson.com/en-gb/who-we-are/",
        },
      ],
      consequences: {
        own: "You own the promise to buyers. Start at a scale you can make and support.",
        license:
          "A better-fit partner may help. Set a time limit so talks do not drift.",
        partner:
          "The partner could open doors. Decide who owns the customer and fixes faults.",
        hold: "You can save cash and refine the product. Set the proof needed for a launch.",
      },
      rubric: [
        "Did you distinguish maker incentives from buyer demand?",
        "Did you include factory costs and after-sales help?",
        "Did you use Japan as evidence without assuming Britain is the same?",
        "Did you set brand, service and customer rights for a partner?",
      ],
    },
  },
];
